# Generated by Django 3.0.6 on 2020-06-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_time', models.CharField(blank=True, max_length=30, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('units_done', models.IntegerField(blank=True, null=True)),
                ('type_course', models.CharField(choices=[('V', 'Video'), ('B', 'Book'), ('EB', 'Ebook'), ('T', 'Tutorial')], max_length=2)),
                ('status_course', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('IP', 'In progress')], max_length=2)),
            ],
        ),
    ]
